// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktdplwbjeyounqtuygeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0ZHBsd2JqZXlvdW5xdHV5Z2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDU4NDcsImV4cCI6MjA1OTkyMTg0N30.SeGuu1EY5lBXGR1DpOQjFGO-otqM4OzMEtd7qOaiY1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);